# Generated by Django 4.2 on 2023-06-06 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_username_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(blank=True, default='uploads/default.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
